//go:build !ignore_autogenerated

/*
 * Copyright Sebastian Sch Author.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VFLinkConfig) DeepCopyInto(out *VFLinkConfig) {
	*out = *in
	if in.VLAN != nil {
		in, out := &in.VLAN, &out.VLAN
		*out = new(int)
		**out = **in
	}
	if in.Qos != nil {
		in, out := &in.Qos, &out.Qos
		*out = new(int)
		**out = **in
	}
	if in.VlanProto != nil {
		in, out := &in.VlanProto, &out.VlanProto
		*out = new(string)
		**out = **in
	}
	if in.SpoofChk != nil {
		in, out := &in.SpoofChk, &out.SpoofChk
		*out = new(bool)
		**out = **in
	}
	if in.Trust != nil {
		in, out := &in.Trust, &out.Trust
		*out = new(bool)
		**out = **in
	}
	if in.MinTxRate != nil {
		in, out := &in.MinTxRate, &out.MinTxRate
		*out = new(int)
		**out = **in
	}
	if in.MaxTxRate != nil {
		in, out := &in.MaxTxRate, &out.MaxTxRate
		*out = new(int)
		**out = **in
	}
	if in.LinkState != nil {
		in, out := &in.LinkState, &out.LinkState
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VFLinkConfig.
func (in *VFLinkConfig) DeepCopy() *VFLinkConfig {
	if in == nil {
		return nil
	}
	out := new(VFLinkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VfConfig) DeepCopyInto(out *VfConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.VF != nil {
		in, out := &in.VF, &out.VF
		*out = new(VFLinkConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VfConfig.
func (in *VfConfig) DeepCopy() *VfConfig {
	if in == nil {
		return nil
	}
	out := new(VfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VfConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
