---
apiVersion: v1
kind: Namespace
metadata:
  name: vf-test9
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vf-test1
  namespace: vf-test9
  annotations:
    k8s.v1.cni.cncf.io/resourceName: sriov1/vf
spec:
  config: |-
    {
        "cniVersion": "1.0.0",
        "name": "vf-test1",
        "type": "sriov",
        "vlan": 0,
        "spoofchk": "on",
        "trust": "on",
        "vlanQoS": 0,
        "logLevel": "info",
        "ipam": {
            "type": "host-local",
            "ranges": [
                [
                    {
                        "subnet": "10.0.2.0/24"
                    }
                ]
            ]
        }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vf-test2
  namespace: vf-test9
  annotations:
    k8s.v1.cni.cncf.io/resourceName: sriov2/vf
spec:
  config: |-
    {
        "cniVersion": "1.0.0",
        "name": "vf-test2",
        "type": "sriov",
        "vlan": 0,
        "spoofchk": "on",
        "trust": "on",
        "vlanQoS": 0,
        "logLevel": "info",
        "ipam": {
            "type": "host-local",
            "ranges": [
                [
                    {
                        "subnet": "10.0.2.0/24"
                    }
                ]
            ]
        }
    }
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: vf-test9
  name: vf-test9
spec:
  spec:
    devices:
      requests:
      - name: vf
        exactly:
          deviceClassName: sriovnetwork.openshift.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vf-test9
  name: pod0
  labels:
    app: pod0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod0
  template:
    metadata:
      labels:
        app: pod0
      annotations:
        k8s.v1.cni.cncf.io/networks: vf-test1,vf-test2
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: ctr0
        image: quay.io/schseba/toolbox:latest
        command:
          - /bin/bash
          - -c
          - sleep INF
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
        resources:
          claims:
          - name: sriov1
          - name: sriov2
      resourceClaims:
      - name: sriov1
        resourceClaimTemplateName: vf-test9
      - name: sriov2
        resourceClaimTemplateName: vf-test9
