// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/k8snetworkplumbingwg/dra-driver-sriov/pkg/devicestate (interfaces: DeviceInfoStore)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_deviceinfostore.go -package=mock github.com/k8snetworkplumbingwg/dra-driver-sriov/pkg/devicestate DeviceInfoStore
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	v1 "github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceInfoStore is a mock of DeviceInfoStore interface.
type MockDeviceInfoStore struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceInfoStoreMockRecorder
	isgomock struct{}
}

// MockDeviceInfoStoreMockRecorder is the mock recorder for MockDeviceInfoStore.
type MockDeviceInfoStoreMockRecorder struct {
	mock *MockDeviceInfoStore
}

// NewMockDeviceInfoStore creates a new mock instance.
func NewMockDeviceInfoStore(ctrl *gomock.Controller) *MockDeviceInfoStore {
	mock := &MockDeviceInfoStore{ctrl: ctrl}
	mock.recorder = &MockDeviceInfoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceInfoStore) EXPECT() *MockDeviceInfoStoreMockRecorder {
	return m.recorder
}

// CleanDeviceInfoForDP mocks base method.
func (m *MockDeviceInfoStore) CleanDeviceInfoForDP(resourceName, deviceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanDeviceInfoForDP", resourceName, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanDeviceInfoForDP indicates an expected call of CleanDeviceInfoForDP.
func (mr *MockDeviceInfoStoreMockRecorder) CleanDeviceInfoForDP(resourceName, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanDeviceInfoForDP", reflect.TypeOf((*MockDeviceInfoStore)(nil).CleanDeviceInfoForDP), resourceName, deviceID)
}

// SaveDeviceInfoForDP mocks base method.
func (m *MockDeviceInfoStore) SaveDeviceInfoForDP(resourceName, deviceID string, devInfo *v1.DeviceInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDeviceInfoForDP", resourceName, deviceID, devInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDeviceInfoForDP indicates an expected call of SaveDeviceInfoForDP.
func (mr *MockDeviceInfoStoreMockRecorder) SaveDeviceInfoForDP(resourceName, deviceID, devInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDeviceInfoForDP", reflect.TypeOf((*MockDeviceInfoStore)(nil).SaveDeviceInfoForDP), resourceName, deviceID, devInfo)
}
